name: myDocker

on:
  workflow_dispatch:
  push:
    branches:
      - clannad
  pull_request:

env:
  IMAGE_NAME: biliexper

jobs:

  docker:
    # Ensure test job passes before pushing image.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file ./Docker/Dockerfile --tag $IMAGE_NAME

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to _ + lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker tag $IMAGE_ID:$VERSION ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION